# Generated by Django 3.1.6 on 2021-03-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=90)),
                ('roll', models.IntegerField()),
                ('email', models.EmailField(max_length=80)),
                ('addmission_confirm', models.DateTimeField()),
            ],
        ),
    ]
